### PR TITLE
Updated documentation for NG

### PR DESCRIPTION
**Pull request by thomaspreece**
Added in details about new conditional compiling flags, Pre/Post compile scripts and fixed a few errors in the documentation due to updates to IDE and bmk. Also changed the logo to distinguish it from normal Blitzmax (Feel free to change logo, I just quickly nicked the logo from the website, it'll do as a placeholder for now)

### CODE REVIEW

**Comment by GWRon** [comment]
Maybe we should clear the wave tutorial licence before adding it to the repo.

Also I am not sure whether adding the tutorial at all is "needed". Compared to just providing it on the project website (bmx-ng.com or so).

Aside of this I understand the advantages on having a introductory tutorial on board.

Other opinions?

**Comment by thomaspreece** [comment]
Having a tutorial built in is a good idea as its something that is lacking from BlitzMax and will allow learning the language offline. 

By "Maybe we should clear the wave tutorial licence before adding it to the repo." do you mean remove the link to the online version of the tutorial?

**Comment by GWRon** [comment]
No... i was talking about checking what licence the tutorial is publishef under. And if the project is allowed to include the tutorial files.

**Comment by woollybah** [comment]
Looking good. Thanks for all the work you've put into this!

**Comment by GWRon** [comment]
Maybe we should ask him (tuplo):
http://www.blitzmax.com/Account/showuser.php?id=1367

I assume he gives the OK but better asked in front than running into trouble later.

**Comment by thomaspreece** [comment]
Ive sent him an email and await a reply. (Assuming that his email is still active)

**Comment by thomaspreece** [comment]
Reply to email:

Hi Thomas!

I am very happy for you to do that.

The blitzmax/monkey open license? I am not so attached to what you use. Do
you have any suggestions?

Happy to hear that my guide still could be useful for some 

All the best,
Patrik

**Comment by GWRon** [comment]
NG uses zlib/libpng - which is a very liberate licence which allows almost any usage (but keeps the authorship / ownership).
Maybe Patrik does agree to use that licence (BlitzMax is open sourced under zlib/libpng too).

Anyway: the guide is using the "non strict" variant. So maybe it is a good idea to "superstrict" everything in the documents because NG only supports "superstrict".

bye
Ron

**Comment by woollybah** [comment]
NG works with both Strict and SuperStrict.

I was working through the guide last night. I'm about half-way through tweaking and updating parts of it - mostly to make it "at least" Strict. I'm also considering changing some of the coding style - like the author's preference for putting If statements on long, single lines, which I think is untidy and often confusing (especially when it is meant to be an introductory guide).

**Comment by GWRon** [comment]
> I'm also considering changing some of the coding style - like the author's preference for putting If statements on long, single lines

Thats the problem with enforced single line if-conditions (or the concatenation via `..`) (in addition to allowing "then" for single- and multi-line ifs.

If you rewrite the guide, you might even replace shorthand codes ($ %  ... ) with their long forms (string int ...) as especially for a beginner this is not "intuitive" and just something more they have to "remember"/learn.

**Comment by thomaspreece** [comment]
Author of tutorial is happy to put it on the same license as NG.

**Comment by woollybah** [comment]
zlib is a software license, which doesn't really fit here - I noticed as I was adding it to the docs.
The love2d project appears to also have had this issue, and came up with this : https://love2d.org/wiki/License (The FreeBSD Documentation license). I suggest we do something similar.

**Pull request merged**
